# Generated by Django 3.1.8 on 2023-03-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='whether poll is open for voting'),
        ),
    ]
